apiVersion: v2
name: paperless-ngx
description: >-
  A community Helm chart for Paperless-ngx, a document management system
  that transforms physical documents into a searchable online archive.
type: application
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/v2.20.15/resources/logo/web/svg/square.svg
home: https://github.com/CodeOpsMS/paperless-ngx-helm-chart
version: "0.3.21"
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: "2.20.15"
keywords:
  - paperless
  - paperless-ng
  - paperless-ngx
  - dms
  - document
maintainers:
  - name: codeopsms
    email: codeopsms@users.noreply.github.com
    url: https://github.com/CodeOpsMS
sources:
  - https://github.com/CodeOpsMS/paperless-ngx-helm-chart
  - https://github.com/paperless-ngx/paperless-ngx
  - https://codeberg.org/wrenix/helm-charts/src/branch/main/paperless-ngx
dependencies:
  - name: postgresql
    version: "^16.5.6"
    repository: "oci://docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: valkey
    version: "0.9.4"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.internal
