---
{{- $fullname := include "paperless-ngx.fullname" . }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $fullname) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  annotations:
    "checksum/config": {{ toYaml .Values.config | sha256sum }}
    "checksum/env": {{ toYaml .Values.env | sha256sum }}

data:
  {{- with .Values.config.url }}
  PAPERLESS_URL: {{ toYaml . | b64enc }}
  {{- else }}
  {{- $ingressTLS := ne ( len .Values.ingress.tls ) 0 }}
  PAPERLESS_URL: {{ printf "%s://%s" (ternary "https" "http" $ingressTLS) (first .Values.ingress.hosts).host | b64enc }}
  {{- end }}
  {{- if .Values.valkey.internal }}
  PAPERLESS_REDIS: {{ printf "redis://%s:%.f/%.f" (include "paperless-ngx.valkeyFullname" $) .Values.valkey.service.port .Values.valkey.dbid | b64enc }}
  {{- else if not .Values.config.redis.existingSecret.name }}
  {{- with .Values.config.redis.url }}
  PAPERLESS_REDIS: {{ toYaml . | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.config.redis.prefix }}
  PAPERLESS_REDIS_PREFIX: {{ toYaml . | b64enc }}
  {{- end }}

  {{- with .Values.config.database }}
  {{- with .engine }}
  PAPERLESS_DBENGINE: {{ toYaml . | b64enc }}
  {{- end }}
  {{- with .host }}
  PAPERLESS_DBHOST: {{ toYaml . | b64enc }}
  {{- else }}
  PAPERLESS_DBHOST: {{ include "paperless-ngx.postgresqlFullname" $ | b64enc }}
  {{- end }}
  {{- with .port }}
  PAPERLESS_DBPORT: {{ toYaml . | b64enc }}
  {{- end }}
  {{- with .name }}
  PAPERLESS_DBNAME: {{ toYaml . | b64enc }}
  {{- end }}
  {{- with .user }}
  PAPERLESS_DBUSER: {{ toYaml . | b64enc }}
  {{- end }}
  {{- if and (not .existingSecret.name) .password }}
  PAPERLESS_DBPASS: {{ toYaml .password | b64enc }}
  {{- end }}
  {{- with .options }}
  PAPERLESS_DB_OPTIONS: {{ toYaml . | b64enc }}
  {{- end }}
  {{- end }}{{/* end-with .config.database */}}

  {{- with .Values.config.apps }}
  PAPERLESS_APPS: {{ toYaml . | b64enc }}
  {{- end }}
  {{- with .Values.config.oidcProviders }}
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: {{ toJson . | b64enc }}
  {{- end }}

  {{- if not .Values.config.secretKey.existingSecret.name }}
  PAPERLESS_SECRET_KEY: {{ dig "data" "PAPERLESS_SECRET_KEY" "" $secret
    | b64dec
    | default (randAlphaNum 64)
    | b64enc }}
  {{- end }}

  {{- range $name, $value := .Values.env }}
  {{- if not (kindIs "map" $value) }}
  {{ $name }}: {{ toString $value | b64enc }}
  {{- end }}
  {{- end }}
